export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" style={{ overflow: 'hidden' }}>
      <body
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: '100vh',
          width: '100vw',
          margin: 0,
          backgroundColor: '#1a202c',
        }}
      >
        {children}
      </body>
    </html>
  )
}
