import ChakraWrapper from './chakra-provider'

export const metadata = {
  title: 'Next.js + Chakra',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <div>
          <ChakraWrapper>{children}</ChakraWrapper>
        </div>
      </body>
    </html>
  )
}
