name: Deploy Next.js to EC2 on dev push

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Build and Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 18
      - name: Check Node v
        run: node -v

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_ICE_SERVER_URL=${{ secrets.NEXT_PUBLIC_ICE_SERVER_URL }}" >> .env.local
          echo "NEXT_PUBLIC_STREAM_SERVER_URL=${{ secrets.NEXT_PUBLIC_STREAM_SERVER_URL }}" >> .env.local
          echo "NEXT_PUBLIC_RTSPTOWEB_HOST=${{ secrets.NEXT_PUBLIC_RTSPTOWEB_HOST }}" >> .env.local
          echo "NEXT_PUBLIC_TURN_USERNAME=${{ secrets.NEXT_PUBLIC_TURN_USERNAME }}" >> .env.local
          echo "NEXT_PUBLIC_TURN_PASSWORD=${{ secrets.NEXT_PUBLIC_TURN_PASSWORD }}" >> .env.local
          echo "NEXT_PUBLIC_SIGNALING_URL=${{ secrets.NEXT_PUBLIC_SIGNALING_URL }}" >> .env.local

      - name: Build Next.js app
        run: npm run build

      - name: Deploy entire project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.AWS_WEBSERVER_KEY }}
          source: '.' # ✅ 전체 프로젝트 복사
          target: '~/app' # 서버 내 배포 위치
          rm: true

      - name: Start app via pm2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.AWS_WEBSERVER_KEY }}
          script: |
            cd ~/app
            npm install --legacy-peer-deps
            npm run build
            pm2 delete nextjs-app || true
            pm2 start node_modules/next/dist/bin/next --name "nextjs-app" -- start -p 3000
